Implementacion bfs
DanielLezcano727/TP2-EDyA1 pull request #5
Opened 2020-06-03 02:17 UTC by FranBlz

2020-06-03 18:53 UTC, DanielLezcano727 requested changes

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.c
> +    if(queue != NULL) {
En esta no se puede hacer esto?
`
return queue == NULL || queue->inicio == NULL
`

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.c
> +    if(queue != NULL && queue->inicio != NULL) {
Aca creo que estaria copado llamara a cola_es_vacia
`
return cola_es_vacia(queue) ? NULL : queue->inicio->dato;
`

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.c
> +    if(queue != NULL && data != NULL) {
No entiendo lo de data aca. Porque si te fijas aca, vamos a tener perdida de memoria cuando data sea NULL, ya que primero lo alocas y despues guardarias NULL.
Si queres ver este caso, podrias hacer al principio de la funcion un
`
if(data == NULL)
  return NULL;
`

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.c
> +    return queue;
Y ojo que aca si queue es NULL, el nodo no lo devolves, pero ya lo creaste

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.c
> +    return queue;
De todas formas, yo la haria de esta manera:
```
if(data == NULL || queue == NULL)
  return NULL;
crear_dato //De la misma manera que lo haces vos
if(cola_es_vacia(queue))
 cola->inicio = newNode;
else
 cola->fin->sig = newNode;

cola->fin = newNode;
return newNode;
```

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.c
> +        if(!cola_es_vacia(queue)) {
Aca cola_es_vacia se fija si queue != NULL, asi que podrias solo llamar a esa funcion

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.c
> +            queue->inicio = queue->inicio->sig;
Y tambien habria que fijarse si inicio es null despues de moverlo y hacer que el fin tambien sea null

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.c
> +    for(;queue->inicio != NULL;) {
Tremendo while te mandaste aca jajajajaja. Yo diria o que le pongas while o que muevas la creacion de temp a la parte de inicializacion del for

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/cola.h
> +Cola* cola_crear();
Esto es nomas decision de diseño. Convendria hacer un typedef Cola* Queue (con otros nombres)?

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/itree.c
> +  ITree aux;
Aca no se podria mover con arbol? Total, es una copia

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/itree.c
> +  for(;!cola_es_vacia(queue);) {
Lo cambiaria por un while

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/itree.c
> +    visit(aux);
Pregunta importante. visit aux o visit aux->intervalo? En las funciones que haciamos, la funcion visitante era sobre el dato que guardaban, para mi iria mejor un visit(aux->intervalo), y si elegimos hacerlo asi, habria que cambiar la signatura de la funcion visitante

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/makefile
> +ESTRUCTURA1 = itree
Creo que quedaria mejor arbol en vez de estructura1

2020-06-03 18:53 UTC, DanielLezcano727 commented on src/itree.c
> +  }else if(intervalo->bgn < arbol->intervalo->bgn || (intervalo->bgn == arbol->intervalo->bgn && intervalo->end < arbol->intervalo->end)){
Si cambias esto en esta PR, habria que cambiar itree_eliminar tambien

2020-06-04 01:29 UTC, FranBlz commented on src/itree.c
> +    visit(aux);
Ahi lo cambie. Igualmente, lo puse asi porque de esa manera podemos visitar tambien el dato maySub, dejo comentada esa opcion y pongo la de leer intervalos como definitiva.

2020-06-04 01:33 UTC, FranBlz commented on src/cola.h
> +Cola* cola_crear();
No estaria mal, pero creo que se puede revisar cuando repensemos los nombres de itree

2020-06-04 01:43 UTC, FranBlz commented on src/cola.c
> -    newNode->dato = malloc(sizeof(INode));
Esto era al pedo porque newNode->dato es ITree, por lo que aca habia perdida de memoria

2020-06-04 01:58 UTC, merged